# The west manifest file (west.yml) for the NXP ZSDK
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.
#
#     [manifest]
#     path = zsdk
#
manifest:
  version: "1.2"

  # "remotes" is a list of locations where git repositories are cloned
  # and fetched from.
  remotes:
    - name: nxp
      url-base: https://github.com/NXP
    - name: nxp-zsdk
      url-base: https://github.com/nxp-zephyr
    - name: nxp-mcuxpresso
      url-base: https://github.com/nxp-mcuxpresso
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  # If not otherwise specified, the projects below should be obtained
  # from the zsdk remote.
  defaults:
    remote: nxp-zsdk

  group-filter: [+optional, -bifrost]

  # "projects" is a list of git repositories to populate NXP Zephyr downstream
  # workspace.
  projects:

    - name: zephyr
      repo-path: nxp-zephyr
      revision: 184ca82dcd9d69e957497e73a2ac71ba1461dd59
      import:
        #
        # ZSDK imports the contents of nxp-zephyr/west.yml at the above
        # revision. Only the projects explicitly named in the
        # following allowlist are imported.
        #
        # If there is an override of one of the Zephyr modules,
        # remove it from the name-allowlist and add the project
        # explicitly below the list.
        #
        name-allowlist:
          - TraceRecorderSource
          - canopennode
          - chre
          - cmsis
          - cmsis-dsp
          - cmsis-nn
          - cmsis_6
          - edtt
          - fatfs
          - hal_nxp
          - hal_st
          - hal_xtensa
          - liblc3
          - libmctp
          - libsbc
          - libmetal
          - littlefs
          - loramac-node
          - lvgl
          - lz4
          - mcuboot
          - mipi-sys-t
          - net-tools
          - open-amp
          - picolibc
          - segger
          - tinycrypt
          - uoscore-uedhoc
          - zcbor
          - zscilib
          - openthread

    # For internal NXP development support
    - name: bifrost
      west-commands: scripts/west_commands.yml
      repo-path: bifrost
      revision: d50c2636540cae9f933d77095e29d5ff093c61cc
      groups:
        - bifrost

    #
    # NXP based overrides of Zephyr modules and additional
    # added modules
    #
    - name: hal_nxp
      revision: nxp-v4.3.0
      path: modules/hal/nxp
      groups:
        - hal
    - name: els_pkc
      remote: nxp
      repo-path: els_pkc
      revision: 71d4a89c03fb32e618ee02c0cd54b3fc92736c96
      path: modules/crypto/els_pkc
      groups:
        - crypto
    - name: psa_crypto_driver
      remote: nxp
      repo-path: psa_crypto_driver
      revision: 838ecbdbbd50a8c2e0c00e6c05bceb180d6285fe
      path: modules/crypto/psa_crypto_driver
      groups:
        - crypto
    - name: mbedtls
      remote: nxp
      repo-path: nxp_mbedtls
      revision: 0acd394228698278d8cff257340c20022d3b0c07
      path: modules/crypto/mbedtls
      groups:
        - crypto
    - name: trusted-firmware-m
      remote: nxp
      repo-path: nxp_tf-m
      revision: 3b3595f16523bf8ab1366c2c44f2f548acea61ec
      path: modules/tee/tf-m/trusted-firmware-m
      groups:
        - tee
    - name: psa-arch-tests
      remote: nxp
      repo-path: nxp_psa_arch_test
      revision: 227f44226c64471bc61767b9c69de75345c7602a
      path: modules/tee/tf-m/psa-arch-tests
      groups:
        - tee
    - name: tf-m-tests
      revision: a90702bcb8fadb6f70daf0ffbb13888dfe63fc99
      path: modules/tee/tf-m/tf-m-tests
      remote: zephyrproject
      groups:
        - tee
    - name: hostap
      repo-path: hostap
      revision: 43a55cc35d7dc4a238daeb8448fdf07ac4f356b3
      path: modules/lib/hostap
    - name: wifi_nxp
      remote: nxp
      repo-path: wifi_nxp
      revision: 408adfbb2ac45cd37fef7d5f6f84e8a4def960f6
      path: modules/hal/nxp/mcux/middleware/wifi_nxp
    - name: wifi_nb_fw
      remote: nxp
      repo-path: wifi_nb_fw
      revision: 767ceb730e672917dee229d03b878c7e0fe13f9c
      path: modules/hal/nxp/zephyr/blobs/
    - name: nxp_iot_agent
      remote: nxp
      repo-path: el2go-agent
      revision: 9c48cee6f5d200b3977028cc79b53995de76fd7a
      path: modules/lib/nxp_iot_agent
    - name: freemaster
      remote: nxp-mcuxpresso
      repo-path: mcux-freemaster
      revision: 52dd288482aab2a13b8c21926d0fe27ea32eb44d
      path: modules/debug/freemaster
    - name: freemaster-samples
      remote: nxp-zsdk
      repo-path: fmstr-zephyr-samples
      revision: 412487bedebc43c1fd40cb76d7d41f989c2f8063
      path: zsdk/samples/freemaster

    # Add any additional third-party repositories.

  self:
    path: zsdk
    # Configure west extensions.
    #west-commands: scripts/west-commands.yml
